language: go

go:
  - 1.12.x

before_install:
  - go get -t -v ./...

before_script: cd $GOPATH/src/github.com/badstreff/terraform-provider-vmm/pkg
script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...

after_success:
  - bash <(curl -s https://codecov.io/bash)