package getting

import (
	"reflect"
	"testing"
)

func TestDiskGetByID(t *testing.T) {
	doer := MockDoer{}
	doer.StatusCode = 200
	doer.Data = `{
    "Accessibility": "Public",
    "AddedTime": "2018-10-10T07:40:01.5-05:00",
    "CloudId": null,
    "Description": "To be used as a base drive to create a new virtual machine or as an additional data drive.",
    "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs",
    "Enabled": true,
    "FamilyName": null,
    "HostVolumeId": null,
    "ID": "EXAMPLE-GUID-001",
    "IsOrphaned": false,
    "IsResourceGroup": null,
    "JobGroupId": null,
    "LibraryGroup": "",
    "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
    "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhdx",
    "MaximumSize": "17179869184",
    "ModifiedTime": "2018-10-10T08:21:30.367-05:00",
    "Name": "Blank Disk - Small.vhdx",
    "Namespace": "Global",
    "OperatingSystem": "None",
    "OperatingSystemId": null,
    "OperatingSystemInstance": {
        "Architecture": "x86",
        "Description": "There is no Operating System associated with this object",
        "Edition": null,
        "Name": "None",
        "OSType": "Other",
        "ProductType": null,
        "Version": null
    },
    "Owner": {
        "RoleID": null,
        "RoleName": null,
        "UserName": null
    },
    "OwnerSid": null,
    "ParentDiskId": null,
    "Release": null,
    "ReleaseTime": null,
    "SANCopyCapable": false,
    "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhdx",
    "Shielded": false,
    "Size": "4194304",
    "StampId": "EXAMPLE-GUID-002",
    "State": "Normal",
    "Tag": [],
    "TemplateId": null,
    "Type": null,
    "VHDType": "DynamicallyExpanding",
    "VMId": null,
    "VirtualizationPlatform": "HyperV",
    "VolumeSignatureCatalogIssuerName": null,
    "VolumeSignatureCatalogName": null,
    "VolumeSignatureCatalogVersion": null,
    "odata.metadata": "https://VMM.EXAMPLE.COM:8090/SC2012R2/VMM/Microsoft.Management.Odata.svc/$metadata#VirtualHardDisks/@Element"
}`

	diskService := NewVirtualHardDiskService(doer, "", "")
	disk, err := diskService.GetByID("")
	if err != nil {
		t.Errorf("Error attempting to parse disk")
		t.Errorf("%v", err)
	}
	expected := VirtualHardDisk{
		Accessibility:   sPtr("Public"),
		AddedTime:       sPtr("2018-10-10T07:40:01.5-05:00"),
		Description:     sPtr("To be used as a base drive to create a new virtual machine or as an additional data drive."),
		Directory:       sPtr("\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs"),
		Enabled:         bPtr(true),
		ID:              sPtr("EXAMPLE-GUID-001"),
		IsOrphaned:      bPtr(false),
		LibraryGroup:    sPtr(""),
		LibraryShareID:  sPtr("1638a765-fb67-436c-8bf8-b374ed9a1acb"),
		Location:        sPtr("\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhdx"),
		MaximumSize:     sPtr("17179869184"),
		ModifiedTime:    sPtr("2018-10-10T08:21:30.367-05:00"),
		Name:            sPtr("Blank Disk - Small.vhdx"),
		Namespace:       sPtr("Global"),
		OperatingSystem: sPtr("None"),
		OperatingSystemInstance: &OperatingSystem{
			Architecture: sPtr("x86"),
			Description:  sPtr("There is no Operating System associated with this object"),
			Name:         sPtr("None"),
			OSType:       sPtr("Other"),
		},
		Owner:                  &UserAndRole{},
		SANCopyCapable:         bPtr(false),
		SharePath:              sPtr("\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhdx"),
		Shielded:               bPtr(false),
		Size:                   sPtr("4194304"),
		StampID:                sPtr("EXAMPLE-GUID-002"),
		State:                  sPtr("Normal"),
		Tag:                    make([]*string, 0),
		VHDType:                sPtr("DynamicallyExpanding"),
		VirtualizationPlatform: sPtr("HyperV"),
	}
	if !reflect.DeepEqual(*disk, expected) {
		t.Errorf("Disks not equal")
		t.Errorf("%v", disk)
		t.Errorf("%v", expected)
	}
}

func TestDiskGetAll(t *testing.T) {
	doer := MockDoer{}
	doer.StatusCode = 200
	doer.Data = `{
    "odata.metadata": "https://VMM.EXAMPLE.COM:8090/SC2012R2/VMM/Microsoft.Management.Odata.svc/$metadata#VirtualHardDisks",
    "value": [
        {
            "Accessibility": "Public",
            "AddedTime": "2018-10-10T07:40:01.5-05:00",
            "CloudId": null,
            "Description": "To be used as a base drive to create a new virtual machine or as an additional data drive.",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "9298a2ff-ea58-4bc5-9c97-6ec04439609f",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhdx",
            "MaximumSize": "17179869184",
            "ModifiedTime": "2018-10-10T08:21:30.367-05:00",
            "Name": "Blank Disk - Small.vhdx",
            "Namespace": "Global",
            "OperatingSystem": "None",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "There is no Operating System associated with this object",
                "Edition": null,
                "Name": "None",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhdx",
            "Shielded": false,
            "Size": "4194304",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2018-10-10T07:39:59.7-05:00",
            "CloudId": null,
            "Description": "To be used as a base drive to create a new virtual machine or as an additional data drive.",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "391d3247-fe90-4dee-b45f-f7ea088b2ef2",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhd",
            "MaximumSize": "17179869184",
            "ModifiedTime": "2018-10-10T08:21:30.053-05:00",
            "Name": "Blank Disk - Small.vhd",
            "Namespace": "Global",
            "OperatingSystem": "None",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "There is no Operating System associated with this object",
                "Edition": null,
                "Name": "None",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Small.vhd",
            "Shielded": false,
            "Size": "35328",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2019-04-22T14:04:37.977-05:00",
            "CloudId": null,
            "Description": "Windows Server 2016 Template GUI_disk_1",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\Windows Templates\\Windows Server 2016 Template GUI",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "30004ac0-eceb-4a41-bf19-ad38e44e75a6",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\Windows Templates\\Windows Server 2016 Template GUI\\Windows Server 2016 Template GUI_disk_1.vhdx",
            "MaximumSize": "42949672960",
            "ModifiedTime": "2019-04-22T17:42:41-05:00",
            "Name": "Windows Server 2016 Template GUI_disk_1",
            "Namespace": "Global",
            "OperatingSystem": "Unknown",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "Virtual Machine Manager was unable to determine the operating system for this object.",
                "Edition": null,
                "Name": "Unknown",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\Windows Templates\\Windows Server 2016 Template GUI\\Windows Server 2016 Template GUI_disk_1.vhdx",
            "Shielded": false,
            "Size": "23358078976",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2018-12-17T09:53:47.213-06:00",
            "CloudId": null,
            "Description": "TestVMTemplate_disk_1",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\Test_Cloud\\TestVMTemplate",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "b6cb7c0d-d7ee-42bc-97ef-e9d49af5626e",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\Test_Cloud\\TestVMTemplate\\TestVMTemplate_disk_1.vhdx",
            "MaximumSize": "42949672960",
            "ModifiedTime": "2018-12-17T11:26:02.647-06:00",
            "Name": "TestVMTemplate_disk_1",
            "Namespace": "Global",
            "OperatingSystem": "Unknown",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "Virtual Machine Manager was unable to determine the operating system for this object.",
                "Edition": null,
                "Name": "Unknown",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\Test_Cloud\\TestVMTemplate\\TestVMTemplate_disk_1.vhdx",
            "Shielded": false,
            "Size": "4194304",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2019-04-22T13:24:38.153-05:00",
            "CloudId": null,
            "Description": "ha-rhel-7_disk_1",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\RHEL Templates\\ha-rhel-7",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "96a58539-70ee-40b9-aca5-97778ce5f59d",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\RHEL Templates\\ha-rhel-7\\ha-rhel-7_disk_1.vhdx",
            "MaximumSize": "26843545600",
            "ModifiedTime": "2019-04-22T13:42:37.88-05:00",
            "Name": "ha-rhel-7_disk_1",
            "Namespace": "Global",
            "OperatingSystem": "Unknown",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "Virtual Machine Manager was unable to determine the operating system for this object.",
                "Edition": null,
                "Name": "Unknown",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\RHEL Templates\\ha-rhel-7\\ha-rhel-7_disk_1.vhdx",
            "Shielded": false,
            "Size": "4194304",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2018-10-10T07:40:01.13-05:00",
            "CloudId": null,
            "Description": "To be used as a base drive to create a new virtual machine or as an additional data drive.",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "53a92f9b-7481-4cd5-80e9-0e000a6f72f1",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Large.vhd",
            "MaximumSize": "64424509440",
            "ModifiedTime": "2018-10-10T08:21:30.443-05:00",
            "Name": "Blank Disk - Large.vhd",
            "Namespace": "Global",
            "OperatingSystem": "None",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "There is no Operating System associated with this object",
                "Edition": null,
                "Name": "None",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Large.vhd",
            "Shielded": false,
            "Size": "125440",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2018-12-21T09:54:02.993-06:00",
            "CloudId": null,
            "Description": "RHEL-Micro-Template_disk_1",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\RHEL Templates\\RHEL-Micro-Template",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "a221e888-4f3c-4617-bb17-f970ec7d151b",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\RHEL Templates\\RHEL-Micro-Template\\RHEL-Micro-Template_disk_1.vhdx",
            "MaximumSize": "26843545600",
            "ModifiedTime": "2018-12-21T14:26:02.92-06:00",
            "Name": "RHEL-Micro-Template_disk_1",
            "Namespace": "Global",
            "OperatingSystem": "Unknown",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "Virtual Machine Manager was unable to determine the operating system for this object.",
                "Edition": null,
                "Name": "Unknown",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\RHEL Templates\\RHEL-Micro-Template\\RHEL-Micro-Template_disk_1.vhdx",
            "Shielded": false,
            "Size": "4194304",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2018-10-10T07:40:02.057-05:00",
            "CloudId": null,
            "Description": "To be used as a base drive to create a new virtual machine or as an additional data drive.",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs",
            "Enabled": true,
            "FamilyName": null,
            "HostVolumeId": null,
            "ID": "358c0e46-1290-4f99-ba40-b7c271a46433",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Large.vhdx",
            "MaximumSize": "64424509440",
            "ModifiedTime": "2018-10-10T08:21:30.52-05:00",
            "Name": "Blank Disk - Large.vhdx",
            "Namespace": "Global",
            "OperatingSystem": "None",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "x86",
                "Description": "There is no Operating System associated with this object",
                "Edition": null,
                "Name": "None",
                "OSType": "Other",
                "ProductType": null,
                "Version": null
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": null,
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Blank Disk - Large.vhdx",
            "Shielded": false,
            "Size": "4194304",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        },
        {
            "Accessibility": "Public",
            "AddedTime": "2018-11-07T09:51:07.737-06:00",
            "CloudId": null,
            "Description": "",
            "Directory": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs",
            "Enabled": true,
            "FamilyName": "",
            "HostVolumeId": null,
            "ID": "2a8cc33f-138d-430e-bc35-57ea390aa65a",
            "IsOrphaned": false,
            "IsResourceGroup": null,
            "JobGroupId": null,
            "LibraryGroup": "",
            "LibraryShareId": "1638a765-fb67-436c-8bf8-b374ed9a1acb",
            "Location": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Windows Server 2016 (GUI) v2.vhdx",
            "MaximumSize": "42949672960",
            "ModifiedTime": "2019-04-11T13:58:09.0140615-05:00",
            "Name": "Windows Server 2016 (GUI) v2.vhdx",
            "Namespace": "Global",
            "OperatingSystem": "Windows Server 2016 Standard",
            "OperatingSystemId": null,
            "OperatingSystemInstance": {
                "Architecture": "amd64",
                "Description": "Windows Server 2016 Standard",
                "Edition": "Standard",
                "Name": "Windows Server 2016 Standard",
                "OSType": "Windows",
                "ProductType": "VER_NT_SERVER",
                "Version": "10.0"
            },
            "Owner": {
                "RoleID": null,
                "RoleName": null,
                "UserName": null
            },
            "OwnerSid": null,
            "ParentDiskId": null,
            "Release": "",
            "ReleaseTime": null,
            "SANCopyCapable": false,
            "SharePath": "\\\\VMM.EXAMPLE.COM\\MSSCVMMLibrary\\VHDs\\Windows Server 2016 (GUI) v2.vhdx",
            "Shielded": false,
            "Size": "33625735168",
            "StampId": "7287597b-3c5a-45f9-a359-cf575fefe096",
            "State": "Normal",
            "Tag": [],
            "TemplateId": null,
            "Type": null,
            "VHDType": "DynamicallyExpanding",
            "VMId": null,
            "VirtualizationPlatform": "HyperV",
            "VolumeSignatureCatalogIssuerName": null,
            "VolumeSignatureCatalogName": null,
            "VolumeSignatureCatalogVersion": null
        }
    ]
}`

	expectedNumDisks := 9
	diskService := NewVirtualHardDiskService(doer, "", "")
	disks, err := diskService.GetAll()
	if err != nil {
		t.Errorf("Error attempting to parse disk feed")
		t.Errorf("%v", err)
	}
	if len(disks) != expectedNumDisks {
		t.Errorf("Wrong number of disks returned: expected 9, got %v", len(disks))
	}
}
